### PR TITLE
fix build errors

### PR DESCRIPTION
**Pull request by jennyf19**

### CODE REVIEW

**Comment by jennyf19** [comment]
i guess only PRs into master run the build. i'll try running it anyway and see if this fixes the issues.

**Comment by jennyf19** [comment]
still having issues. i'll resolve them tomorrow: https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=508920&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=6a7ac225-8257-51f6-8eed-20c2e5179b9e

**Comment by jennyf19** [comment]
so this worked: https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=509776&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=fd490c07-0b22-5182-fac9-6d67fe1e939b

**Comment by jmprieur** [comment]
awesome @jennyf19!

**Pull request merged**
